### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by daniel-marcus** [dekoder-org/donation-encourager#1]
To use the donation encourager in dekoder special projects (e.g., https://protest.dekoder.org/en), it would be very convenient to make it usable as an npm package.

I already did some preparations to to the package.json and published it to npm (https://www.npmjs.com/package/donation-encourager), but that's not working yet. I'm working on this (masterplan: provide a transpiled version of the module in the dist-folder and mark it as a new entry point in package.json [instead of src/index.js]).

**Comment by daniel-marcus** [comment]
Btw, @greatestview, is the contributor information correct in [package.json](https://github.com/dekoder-org/donation-encourager/blob/master/package.json)?

**Comment by greatestview** [comment]
Yes, thank you :)

**Comment by daniel-marcus** [comment]
the npm module is already working (more or less) here: https://protest.dekoder.org/motivation
