### ISSUE TITLE
useGradientEffect with extra size contents

### ISSUE THREAD

**Issue by daniel-marcus** [dekoder-org/donation-encourager#2]
Hi @greatestview,

I guess we have to rethink our useGradientEffect within the [blur-Hook](https://github.com/dekoder-org/donation-encourager/blob/master/src/components/app/hooks/blur.js) since it produces something like this on contents with extra width:

<img width="925" alt="Screenshot 2019-11-14 at 17 53 40" src="https://user-images.githubusercontent.com/47091062/68938196-267a5500-079e-11ea-83a6-02c5d980e4ff.png">

(Seen [here](https://www.dekoder.org/de/article/ozgur-garage-kultur-hobbyraum) with intrusivenessLevel 3.)

Do you have an idea how to deal with this?

**Comment by greatestview** [comment]
This should be fixed with commit https://github.com/dekoder-org/donation-encourager/commit/1315a91cde8402f993267d0446efa0d30a6e0a65. :)

**Comment by daniel-marcus** [comment]
Awesome! Thanks, @greatestview
